#### NUMPY

Numpy is a fundamental library for scientific computing in Python.It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

In [4]:
## Create array using numpy
## Create 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)            ## 1 row 5 col

array([[1, 2, 3, 4, 5]])

1 braces for 1 D array      
2 braces for 2 D array     
3 braces for 3 D array      
...

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
## 2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [9]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## Identity matirx

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
## Attributes of Numpy

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape)    # Output : (2,3)
print("Number of dimensions:",arr.ndim)    # Output : 2
print("Size / number of elements:",arr.size)      # Output : 6
print("Data type:",arr.dtype)       # Output : int32 (may vary based on platform)
print("Item size (in bytes):",arr.itemsize)       # Output : 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size / number of elements: 6
Data type: int64
Item size (in bytes): 8


In [14]:
## Numpy vectorized operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element wise addition
print("Addition:",arr1+arr2)

# Element wise Substraction
print("Substraction:",arr1-arr2)

# Element wise Multiplication
print("Multiplication:",arr1*arr2)

# Element wise Division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
## Universal Function

arr=np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
## Array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print(arr[0][0])
print(arr[1:])

1
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [28]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [30]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [31]:
## MOdify element

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [32]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [33]:
# Statistical concept
# To have a mean of 0 and std deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and std deviation
mean=np.mean(data)
std_dev=np.std(data)

# Normlize the data
normalized_data = (data - mean)/ std_dev
print("Normalized data:",normalized_data)

# Output :
# Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
data = np.array([1,2,3,4,5,6,7,8,910])

# Mean
print("Mean:",np.mean(data))

# Median
print("Median:",np.median(data))

# Standard deviation
print("Standard Deviation:",np.std(data))

# VAriance
print("Variance:",np.var(data))


Mean: 105.11111111111111
Median: 5.0
Standard Deviation: 284.5793950706295
Variance: 80985.43209876544


In [39]:
## Logical operartion

data=np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
print(data[data>5])
print(data[(data>5) & (data<8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7]
