# Module: NumPy Assignments
## Lesson: NumPy


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [ ]:
import random
import numpy as np

nums = np.random.randint(1, 100, size=(5,5))
print(nums)
 
nums[:, 2]=1
print(f"\nReplaced all elements of 3 rd column to 1 :")
print(nums)


[[68 14 56 74 32]
 [19 14 15 72 95]
 [49 51 14 12 80]
 [37 68 53 12 70]
 [42 97 73 90 26]]

Replaced all elements of 3 rd column to 1 :
[[68 14  1 74 32]
 [19 14  1 72 95]
 [49 51  1 12 80]
 [37 68  1 12 70]
 [42 97  1 90 26]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [23]:
array = np.arange(1,17).reshape(4,4)
print(array)

print("\nReplaced diagonal elements with 0")
np.fill_diagonal(array ,0)
array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Replaced diagonal elements with 0


array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [6]:
array = np.arange(1,37).reshape(6,6)
print(array)

print("\nExtracted array of 3rd to 5 th row&2nd to 4th column")
print(array[2:5,1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Extracted array of 3rd to 5 th row&2nd to 4th column
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [7]:
array=np.random.randint(1,50, size=(5,5))
print(array)

print("\nExtracted border elements")
border_elements = np.concatenate([array[0, :], array[1:-1, 0], array[1:-1, -1], array[-1, :]])
print(border_elements)

[[12 49  3 37 48]
 [32 22 47 38 28]
 [28 15 40 24 20]
 [12 24 12 27 32]
 [21 30  6 33 17]]

Extracted border elements
[12 49  3 37 48 32 28 12 28 20 32 21 30  6 33 17]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [8]:
array1 = np.random.randint(1,50, size=(3,4))
print(f"Array 1 : \n {array1}")
array2 = np.random.randint(1,50, size=(3,4))
print(f"Array 2 : \n {array2}")

print(f"addition: \n {array1+array2}")
print(f"subtraction: \n {array1-array2}")
print(f"multiplication: \n {array1*array2}")
print(f"division: \n {array1/array2}")

Array 1 : 
 [[35 28 40 13]
 [20 24 45 19]
 [40 36  8 41]]
Array 2 : 
 [[38 26 23 41]
 [ 9 11  7 12]
 [35 26 30 12]]
addition: 
 [[73 54 63 54]
 [29 35 52 31]
 [75 62 38 53]]
subtraction: 
 [[ -3   2  17 -28]
 [ 11  13  38   7]
 [  5  10 -22  29]]
multiplication: 
 [[1330  728  920  533]
 [ 180  264  315  228]
 [1400  936  240  492]]
division: 
 [[0.92105263 1.07692308 1.73913043 0.31707317]
 [2.22222222 2.18181818 6.42857143 1.58333333]
 [1.14285714 1.38461538 0.26666667 3.41666667]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [9]:
array = np.arange(1,17).reshape(4,4)
print(f"Array :\n", array)

row_wise = np.sum(array ,axis=1)
print(f"\nRow wise addition :\n", row_wise)
col_wise = np.sum(array ,axis=0)
print(f"Column wise addition :\n", col_wise)


Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row wise addition :
 [10 26 42 58]
Column wise addition :
 [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [10]:
array = np.random.randint(1,50, size=(5,5))
print(f"Array :\n",array)

# Mean
print(f"\nMean :",np.mean(array))

# Median
print(f"Median :",np.median(array))

# Standard Deviation
print(f"Standard Deviation :",np.std(array))

# Variance
print(f"Variance :",np.var(array))


Array :
 [[ 7  8  7 39 27]
 [45 39 12 28 32]
 [44 11 40 24 34]
 [17 19 45 44 31]
 [24 19 42 39 43]]

Mean : 28.8
Median : 31.0
Standard Deviation : 12.97073629367277
Variance : 168.24


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [11]:
array = np.arange(1,10).reshape(3,3)
print(f"Array :\n",array)

mean = np.mean(array)
std_dev = np.std(array)

normalized_array = (array - mean)/ std_dev
print(f"\nNormalized array :\n", normalized_array)

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized array :
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [12]:
array =  np.random.randint(1,21, size=(3,3))
print(f"Array :\n",array)
array2 = np.random.randint(1,11, size=3)
print(f"1D Array :\n",array2)

# broadcating
print("Resulting array",array+array2)


Array :
 [[ 3  3  7]
 [13 12 13]
 [11 14 15]]
1D Array :
 [9 6 6]
Resulting array [[12  9 13]
 [22 18 19]
 [20 20 21]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [13]:
array = np.random.randint(1,21, size=(4,4))
print(f"Array :\n", array)
array2 = np.random.randint(1,21, size=4)
print(f"1D Array :\n", array2)

print("Resulting Array :\n",array-array2)

Array :
 [[15 18 12  2]
 [17 13 13 12]
 [ 5 19  6  3]
 [11 16  7 15]]
1D Array :
 [20  2 10 20]
Resulting Array :
 [[ -5  16   2 -18]
 [ -3  11   3  -8]
 [-15  17  -4 -17]
 [ -9  14  -3  -5]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [14]:
array = np.random.randint(1,19, size=(3,3))
print("Array",array)

print("Determinant",np.linalg.det(array))
print("Inverse :\n",np.linalg.inv(array))
print("Eigen Values",np.linalg.eigvals(array))


Array [[ 5 10  3]
 [17  2 16]
 [ 4  7 13]]
Determinant -1666.9999999999989
Inverse :
 [[ 0.05158968  0.06538692 -0.09238152]
 [ 0.09418116 -0.03179364  0.01739652]
 [-0.06658668 -0.0029994   0.0959808 ]]
Eigen Values [ 25.04819958   6.01538317 -11.06358275]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [15]:
array1 = np.random.randint(1,11, size=(2,3))
print(f"Array 1 :\n", array1)
array2 = np.random.randint(1,11, size=(3,2))
print(f"Array 2 :\n",array2)

matrix_multiplication = array1@array2
print(f"Matrix Multiplication :\n",matrix_multiplication)

Array 1 :
 [[3 6 7]
 [3 8 1]]
Array 2 :
 [[8 2]
 [2 8]
 [1 3]]
Matrix Multiplication :
 [[43 75]
 [41 73]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [17]:
array = np.arange(1,10).reshape(3,3)
print(f"Array :\n", array)

a = array.reshape(1,9)
print(f"Reshaped Array :\n",a)
b = array.reshape(9,1)
print(f"Reshaped Array :\n",b)


Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array :
 [[1 2 3 4 5 6 7 8 9]]
Reshaped Array :
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [16]:
array = np.random.randint(1,26, size=(5,5))
print(f"Array :\n", array)

flattened_array = array.reshape(25,)          # OR :-  array.flatten() ....... also works
print(f"Flattened Array :\n",flattened_array)   

reshaped_array = flattened_array.reshape(5,5)
print(f"Reshaped Array :\n",reshaped_array)

Array :
 [[19  5 13 20  2]
 [ 6  7 14  4 15]
 [10 16 12  4 10]
 [18 25  7 25 17]
 [ 1 24 17  7 13]]
Flattened Array :
 [19  5 13 20  2  6  7 14  4 15 10 16 12  4 10 18 25  7 25 17  1 24 17  7
 13]
Reshaped Array :
 [[19  5 13 20  2]
 [ 6  7 14  4 15]
 [10 16 12  4 10]
 [18 25  7 25 17]
 [ 1 24 17  7 13]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [18]:
array = np.random.randint(1,26, size=(5,5))
print(f"Array :\n", array)

row_indices = [0, 0, 4, 4]           # OR :-  corners = arr[[0,0,4,4], [0,4,0,4]] ....... also works                            
col_indices = [0, 4, 0, 4]      
print(f"Corner Elements:\n", array[row_indices,col_indices])


Array :
 [[19  5 24 14  9]
 [25 25 20 17 16]
 [23 11  9  7 10]
 [11  8  2  9  8]
 [ 7 13 11 25 22]]
Corner Elements:
 [19  9  7 22]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [19]:
array = np.random.randint(1,17, size=(4,4))
print(f"Array :\n", array)
                                        
array[array > 10] = 10                    #mask = array > 10                                              
print("Updated Array:\n", array)          #array[mask] = 10 


Array :
 [[ 6 10  5  4]
 [ 2  4  5  2]
 [ 1 10 16  5]
 [11 15  7  5]]
Updated Array:
 [[ 6 10  5  4]
 [ 2  4  5  2]
 [ 1 10 10  5]
 [10 10  7  5]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [20]:
data = [
    ('Fthma',22,48.5),
    ('Shana',20,45),
    ('Baby',26,52)
]
data_type = [('name', 'U5'),('age', int),('weight',float)]                 # 'U<number>' for strings
array = np.array(data, dtype=data_type)
print(f"Array :\n", array)

sorted_array = np.sort(array, order='age')
print(f"Sorted Array :\n", sorted_array)

Array :
 [('Fthma', 22, 48.5) ('Shana', 20, 45. ) ('Baby', 26, 52. )]
Sorted Array :
 [('Shana', 20, 45. ) ('Fthma', 22, 48.5) ('Baby', 26, 52. )]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [21]:
dtype = [('x',int),('y',int)]
data = [(1,2),(3,4),(5,6)]
points = np.array(data, dtype=dtype)
print("Points:\n", points)

# Euclidean distance
x = points['x']
y = points['y']

dx = x[:, np.newaxis] - x[np.newaxis, :]
dy = y[:, np.newaxis] - x[np.newaxis, :]

# 1- [:, np.newaxis] :- Convert 1D(3) to 2D Column(3,1)
#                    [1,3,5] :- [[1],
#                                [3],
#                                [5]]
# 2- [np.newaxis, :] :- Converts it to 2D row (1,3)
#                    [[1],
#                     [3], :- [[1,4,8]]
#                     [5]]
# 1-2 :- oru matrix kittum 1-2 cheythath...dx l x nte differences m dy l y nte differences m aayitlla oru matrix 

distance = np.sqrt(dx**2 + dy**2)
print("Euclidean distances:")
print(distance)

# dx**2 → squares all x-differences
# dy**2 → squares all y-differences
# dx**2 + dy**2 → sums the squares
# np.sqrt(...) → takes the square root → Euclidean distance


Points:
 [(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[1.         2.23606798 5.        ]
 [3.60555128 1.         2.23606798]
 [6.40312424 3.60555128 1.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [22]:
array = np.random.randint(1,17, size=(4,4))
print(f"Array :\n", array)

masked_array = np.ma.masked_greater(array, 10)         # masks all elements >10......Masked elements are ignored in computations
print(f"Masked Array :\n", masked_array)

unmasked_sum = np.sum(masked_array)
print(f"Sum of Unmasked Array :\n", unmasked_sum)




Array :
 [[ 3 12  6 13]
 [ 3 12  4 10]
 [ 7  1  5  8]
 [ 7 13  5  5]]
Masked Array :
 [[3 -- 6 --]
 [3 -- 4 10]
 [7 1 5 8]
 [7 -- 5 5]]
Sum of Unmasked Array :
 64


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
array = np.random.randint(1,10, size=(3,3))
print(f"Array :\n", array)

mask = np.eye(3, dtype=bool)
# np.eye(3) → creates a 3×3 identity matrix
# dtype=bool → converts 1 → True, 0 → False   :- Purpose: True marks diagonal elements → these will be masked                    
masked_array = np.ma.array(array, mask=mask)
print(f"Masked Array :\n", masked_array)

mean = np.mean(masked_array)
print(f"Mean of Unmasked elements :\n", mean)

masked_array[mask] = mean
print(f"Required Array :\n", masked_array)


Array :
 [[7 1 1]
 [5 5 3]
 [5 6 4]]
Masked Array :
 [[-- 1 1]
 [5 -- 3]
 [5 6 --]]
Mean of Unmasked elements :
 3.5
Required Array :
 [[3 1 1]
 [5 3 3]
 [5 6 3]]
